nelmio_api_doc:
    documentation:
        servers:
            -   url: https://https://www.punchlinefest.keepvibz.ovh
                description: API over HTTP
        info:
            title: PunchlineFest API
            description: |
                Application dédiée à l'organisation du festival musical PunchlineFest
                
                [Panel d'administration](https://www.punchlinefest.keepvibz.ovh/admin)
            version: 1.0.0
            x-build: #CommitHash
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            -   Bearer: [ ]
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
